# Generated by Django 4.1.6 on 2023-02-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_expert_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
